version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

  backend_rds:
    ports:
      - "8000:8000"
    build:
      context: ./backend_rds
    environment:
      DB_NAME: my_db
      DB_USER: my_user
      DB_PASSWORD: my_pass
      DB_HOST: postgres
      DB_PORT: 5432
      SECRET_KEY: 'your-secret-key-here'
      DEBUG: 'True'
      CORS_ALLOWED_ORIGINS: 'http://localhost'
    depends_on:
      - postgres
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"

  backend_redis:
    ports:
      - "8001:8001"
    build:
      context: ./backend_redis
    environment:
      SECRET_KEY: 'your-default-secret-key'
      DEBUG: 'True'
      CORS_ALLOWED_ORIGINS: 'http://localhost'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWORD: ''
    depends_on:
      - redis
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8001"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend_rds
      - backend_redis

volumes:
  postgres_data:
  redis_data: